### ISSUE TITLE
Use histogram filtering to filter underlying data table

### ISSUE THREAD

**Issue by whereswaldon** [dominikh/gotraceui#102]
This is a sort of high-level request. I'm asking for a way to achieve something, but I think there are many ways it could be done and I don't know which is most reasonable. In essence, when looking at a histogram of events (like durations of goroutines), I like to filter the histogram to interesting subareas (like examining the long tail in more detail). Then I find crazy outliers that I want to examine on the timeline, but it's hard to find those goroutines on the timeline from the histogram.

This would be easier if any (or several) of the following were possible:

- The histogram had a way to open a table of the raw data that was synchronized with its current view, such that narrowing the histogram narrowed the data in that table
- The histogram added a context menu item for bars representing only a single data element that let me jump to that element
- The "Goroutines" tab (the one next to the histogram) let me sort the data by duration (this is a less general and less cool solution, though perhaps easier).

Making the histogram present a filtered view of the dataset it represents seems like the most generally useful approach, as it can be applied regardless of the dataset being visualized.

**Comment by dominikh** [comment]
aea47c657c7c0180e7754c3b5fbfa002b1608f03 adds an option to filter the goroutine list by the selected range in the histogram.
