### ISSUE TITLE
Web version

### ISSUE THREAD

**Issue by dannykopping** [dominikh/gotraceui#140]
Hey @dominikh, thanks for an amazing project!
I'm creating a tool for continuously pulling execution traces (similar to what [_conprof_](https://promcon.io/2019-munich/slides/lt1-02_conprof-prometheus-but-for-profiles.pdf) used to do for profiles). I'd love to be able to embed this UI so I can retrieve execution traces and view them in the browser.

Is this possible right now?

**Comment by dominikh** [comment]
Thanks!

In theory, Gio supports WebAssembly and you should be able to compile Gotraceui targeting that. In practice, you will at least run into issues with keyboard input and probably performance, and would have to modify Gotraceui so it can load trace data from whatever I/O wasm offers. It's not a mode of operation that's explicitly supported or actively tested right now, and it won't be for the foreseeable future.

**Comment by dannykopping** [comment]
OK super, I'll give it a try. Thanks 👍
