### ISSUE TITLE
Unable to open trace file: time stamps out of order

### ISSUE THREAD

**Issue by JAicewizard** [dominikh/gotraceui#149]
I wanted to try out this tool as an alternative to pprof, as it takes an hour to parse my profiles.

However after adding `-trace ...` as an argument running my benchmarks, I couldn't open them due to the timestamps being out of order.

One thing that I think could mess with the trace is that I used github.com/ianlancetaylor/cgosymbolizer to also get a profile (and trace) of c++ code within CGO, and thread sanitizer. Otherwise this is a completely normal CGO test binary and trace.

go env:
```
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/jaap/.cache/go-build'
GOENV='/home/jaap/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/jaap/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/jaap/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.6'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/jaap/Projects/thesis/faissExt/go/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build590854102=/tmp/go-build -gno-record-gcc-switches'
```

**Comment by dominikh** [comment]
Does `go tool trace` load the trace successfully? If it doesn't then this is probably one of the many instances of the "time stamps out of order" bug (https://github.com/golang/go/issues/16755) that has myriad weird causes. In that case, the only fix is to wait for Go 1.22, which reworks tracing and should no longer suffer from this issue.

**Comment by JAicewizard** [comment]
Oh wow, yeah that is an old bug :O
I tried rerunning with 1.22 but I see that gotraceui doesn't support 1.22 yet

**Comment by dominikh** [comment]
>  I tried rerunning with 1.22 but I see that gotraceui doesn't support 1.22 yet

Unfortunately not, no. I am working on a branch that supports 1.22, but that in turn doesn't support 1.21 yet.

If you can confirm that `go tool trace` also fails to load the 1.21 trace then I will close this issue. Else you have found a bug in our parser.

**Comment by JAicewizard** [comment]
Nope go tool trace also fails, closing now. Thanks for the quick replies!
