### ISSUE TITLE
Replacement character in menu items on macOS

### ISSUE THREAD

**Issue by dmitshur** [dominikh/gotraceui#89]
As seen on macOS with gotraceui v0.1.0:

<img width="305" alt="image" src="https://user-images.githubusercontent.com/1924134/229310396-abe3149b-88f0-4a10-9a18-722918e13f0b.png">

Can probably be reproduced on Linux by changing `key.ModShortcut` to `key.ModCommand` on this line:

https://github.com/dominikh/gotraceui/blob/9688b1d69154c5c6f46462429a5f16e2c4ee84f7/cmd/gotraceui/main.go#L568

Perhaps the Go font is missing the ⌘ glyph and fallback to another font for missing glyphs isn't working (or not setup)? The root problem is possibly in gioui rather than gotraceui.

This seems really minor of course. (The actual shortcut is working, it's only a bug in the rendering.)

**Comment by dominikh** [comment]
⌘ is U+2318. According to fc-query, the Go fonts cover `… 2302 2310 2320-2321 …`, which indeed doesn't include 2318. The Go font is the only font we're using, without any fallbacks.

This is technically our problem, but it is amusing that the only font that Gio includes by default can't render the symbol returned by key.ModShortcut.String, a Gio method.

> This seems really minor of course. (The actual shortcut is working, it's only a bug in the rendering.)

Considering most users are on macOS makes this a somewhat embarrassing first impression.
