### ISSUE TITLE
Ctrl-Scroll zoom broken on Windows

### ISSUE THREAD

**Issue by JackMordaunt** [dominikh/gotraceui#95]
Not sure what is happening, but I cannot zoom on Windows with ctrl-scroll (mouse wheel).

```sh
❯ gotraceui -version
gotraceui.exe v0.2.0
```

Excellent tool by the way!

**Comment by dominikh** [comment]
This will be fixed once https://lists.sr.ht/~eliasnaur/gio-patches/patches/40386 gets merged.
